`import networkx as nx
import matplotlib.pyplot as plt
G = nx.DiGraph()
## G = nx.MultiDiGraph()
## G = nx. Graph()
nodes=["0", "1", "2", "3"]
G.add_nodes_from(nodes)
G.add_edge("1","1")
G.add_edge("1","2")
G.add_edge("1","3")
G.add_edge("2","1")
G.add_edge("3","1")
G.add_edge("4","3")
G.add_edge("4","5")
G.add_edge("4","6")
G.add_edge("5","3")
G.add_edge("5","4")
G.add_edge("5","6")
G.add_edge("6","4")
G.add_edge("6","5")
G.add_edge("6","7")
G.add_edge("7","6")
G.add_edge("7","8")
G.add_edge("7","9")
G.add_edge("8","7")
G.add_edge("9","8")
G.add_edge("9","10")
G.add_edge("9","11")
G.add_edge("9","12")
G.add_edge("10","9")
G.add_edge("11","9")
G.add_edge("11","12")
G.add_edge("12","9")
G.add_edge("12","11")
print(G.nodes())
print(G.edges())
nx.draw(G, with_labels = True)
plt.savefig("simple_path.png") # zapis do pliku png
plt.show() # wyświetlenie